//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beeple_office {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beeple_office.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully deleted all the orders!.
        /// </summary>
        public static string AlertSentenceAllSandwichesPageSuccess {
            get {
                return ResourceManager.GetString("AlertSentenceAllSandwichesPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with retrieving or deleting all the ordered sandwiches! Please try again..
        /// </summary>
        public static string AlertSentenceAllSandwichesPageWrong {
            get {
                return ResourceManager.GetString("AlertSentenceAllSandwichesPageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with the checkin/checkout! Please try again..
        /// </summary>
        public static string AlertSentenceCheckinCheckoutPage {
            get {
                return ResourceManager.GetString("AlertSentenceCheckinCheckoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no event with this date and name..
        /// </summary>
        public static string AlertSentenceEventsNoEvent {
            get {
                return ResourceManager.GetString("AlertSentenceEventsNoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to do that..
        /// </summary>
        public static string AlertSentenceEventsPermission {
            get {
                return ResourceManager.GetString("AlertSentenceEventsPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully changed your present status for the event..
        /// </summary>
        public static string AlertSentenceEventsSuccessfully {
            get {
                return ResourceManager.GetString("AlertSentenceEventsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with the events! Please try again..
        /// </summary>
        public static string AlertSentenceEventsWrong {
            get {
                return ResourceManager.GetString("AlertSentenceEventsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events for this date or between the time you have chosen..
        /// </summary>
        public static string AlertSentenceFilterEventsNoEvents {
            get {
                return ResourceManager.GetString("AlertSentenceFilterEventsNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with the filtering of the events! Please try again..
        /// </summary>
        public static string AlertSentenceFilterEventsWrong {
            get {
                return ResourceManager.GetString("AlertSentenceFilterEventsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick times above 00:00:00 please!.
        /// </summary>
        public static string AlertSentenceFilterRoomsAboveZero {
            get {
                return ResourceManager.GetString("AlertSentenceFilterRoomsAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to make sure you picked a room..
        /// </summary>
        public static string AlertSentenceFilterRoomsCheck {
            get {
                return ResourceManager.GetString("AlertSentenceFilterRoomsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you didn&apos;t chose a date and the times, they have default values..
        /// </summary>
        public static string AlertSentenceFilterRoomsDefault {
            get {
                return ResourceManager.GetString("AlertSentenceFilterRoomsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the end time is later then the start time..
        /// </summary>
        public static string AlertSentenceFilterRoomsLater {
            get {
                return ResourceManager.GetString("AlertSentenceFilterRoomsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no reservations for this room or between the time you have chosen..
        /// </summary>
        public static string AlertSentenceFilterRoomsNoReservations {
            get {
                return ResourceManager.GetString("AlertSentenceFilterRoomsNoReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with the filtering of the rooms! Please try again..
        /// </summary>
        public static string AlertSentenceFilterRoomsWrong {
            get {
                return ResourceManager.GetString("AlertSentenceFilterRoomsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login, please make sure you fill in the username and password!.
        /// </summary>
        public static string AlertSentenceLoginPageFill {
            get {
                return ResourceManager.GetString("AlertSentenceLoginPageFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login, please make sure you enter the right username and password..
        /// </summary>
        public static string AlertSentenceLoginPageRight {
            get {
                return ResourceManager.GetString("AlertSentenceLoginPageRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with the login! Please try again..
        /// </summary>
        public static string AlertSentenceLoginPageWrong {
            get {
                return ResourceManager.GetString("AlertSentenceLoginPageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event couldn&apos;t be made, because there is already an event on that time..
        /// </summary>
        public static string AlertSentenceNewEventAlreadyEvent {
            get {
                return ResourceManager.GetString("AlertSentenceNewEventAlreadyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the inputfields (where, sort event &amp; name) are filled in!.
        /// </summary>
        public static string AlertSentenceNewEventFilled {
            get {
                return ResourceManager.GetString("AlertSentenceNewEventFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully made the event..
        /// </summary>
        public static string AlertSentenceNewEventSuccessfully {
            get {
                return ResourceManager.GetString("AlertSentenceNewEventSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with adding the new event! Please try again..
        /// </summary>
        public static string AlertSentenceNewEventWrong {
            get {
                return ResourceManager.GetString("AlertSentenceNewEventWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room couldn&apos;t be reserved, because there is already a reservation..
        /// </summary>
        public static string AlertSentenceNewRoomReservationAlreadyReservation {
            get {
                return ResourceManager.GetString("AlertSentenceNewRoomReservationAlreadyReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the room&apos;s name or use another one, because it&apos;s already used..
        /// </summary>
        public static string AlertSentenceNewRoomReservationAlreadyUsed {
            get {
                return ResourceManager.GetString("AlertSentenceNewRoomReservationAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room&apos;s name has been added to the list..
        /// </summary>
        public static string AlertSentenceNewRoomReservationRoomNameAdded {
            get {
                return ResourceManager.GetString("AlertSentenceNewRoomReservationRoomNameAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time to start could not be later or the same then the time to end!.
        /// </summary>
        public static string AlertSentenceNewRoomReservationStartTimeBigger {
            get {
                return ResourceManager.GetString("AlertSentenceNewRoomReservationStartTimeBigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have succesfully reserved the room..
        /// </summary>
        public static string AlertSentenceNewRoomReservationSuccessfully {
            get {
                return ResourceManager.GetString("AlertSentenceNewRoomReservationSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with adding the new room reservation! Please try again..
        /// </summary>
        public static string AlertSentenceNewRoomReservationWrong {
            get {
                return ResourceManager.GetString("AlertSentenceNewRoomReservationWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all the fields are filled in yet!.
        /// </summary>
        public static string AlertSentenceOrderSandwichesPageNotYet {
            get {
                return ResourceManager.GetString("AlertSentenceOrderSandwichesPageNotYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have succesfully ordered your sandwiche for .
        /// </summary>
        public static string AlertSentenceOrderSandwichesPagePartOneSuccessfully {
            get {
                return ResourceManager.GetString("AlertSentenceOrderSandwichesPagePartOneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , enjoy your meal!.
        /// </summary>
        public static string AlertSentenceOrderSandwichesPagePartTwoSuccessfully {
            get {
                return ResourceManager.GetString("AlertSentenceOrderSandwichesPagePartTwoSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the responsible for today. After pressing OK, you can see all the orders..
        /// </summary>
        public static string AlertSentenceOrderSandwichesPageResponsible {
            get {
                return ResourceManager.GetString("AlertSentenceOrderSandwichesPageResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the responsible for this day, enjoy your meal..
        /// </summary>
        public static string AlertSentenceOrderSandwichesPageResponsibleNot {
            get {
                return ResourceManager.GetString("AlertSentenceOrderSandwichesPageResponsibleNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with your order! Please try again..
        /// </summary>
        public static string AlertSentenceOrderSandwichesPageWrong {
            get {
                return ResourceManager.GetString("AlertSentenceOrderSandwichesPageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed!.
        /// </summary>
        public static string AlertSentencePasswordPageChanged {
            get {
                return ResourceManager.GetString("AlertSentencePasswordPageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some or all fields are empty, please fill them in to change the password..
        /// </summary>
        public static string AlertSentencePasswordPageEmpty {
            get {
                return ResourceManager.GetString("AlertSentencePasswordPageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with changing your password! Please try again..
        /// </summary>
        public static string AlertSentencePasswordPageWrong {
            get {
                return ResourceManager.GetString("AlertSentencePasswordPageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created your account..
        /// </summary>
        public static string AlertSentenceRegisterPageCreated {
            get {
                return ResourceManager.GetString("AlertSentenceRegisterPageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some or all fields are empty, please fill them in to register..
        /// </summary>
        public static string AlertSentenceRegisterPageEmpty {
            get {
                return ResourceManager.GetString("AlertSentenceRegisterPageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirm password doesn&apos;t match, please fill them in again..
        /// </summary>
        public static string AlertSentenceRegisterPageNotMatch {
            get {
                return ResourceManager.GetString("AlertSentenceRegisterPageNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account with that email has already been taken, please use an other email..
        /// </summary>
        public static string AlertSentenceRegisterPageTaken {
            get {
                return ResourceManager.GetString("AlertSentenceRegisterPageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filled-in E-mail field does not meet the requirements of an e-mail address. Please enter a correct e-mail adress.  .
        /// </summary>
        public static string AlertSentenceRegisterPageValidate {
            get {
                return ResourceManager.GetString("AlertSentenceRegisterPageValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with registering your account! Please try again..
        /// </summary>
        public static string AlertSentenceRegisterPageWrong {
            get {
                return ResourceManager.GetString("AlertSentenceRegisterPageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong with the roomslist! Please try again..
        /// </summary>
        public static string AlertSentenceRoomsPage {
            get {
                return ResourceManager.GetString("AlertSentenceRoomsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AlertTitleAccount {
            get {
                return ResourceManager.GetString("AlertTitleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account duplicate!.
        /// </summary>
        public static string AlertTitleAccountDuplicate {
            get {
                return ResourceManager.GetString("AlertTitleAccountDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty!.
        /// </summary>
        public static string AlertTitleEmpty {
            get {
                return ResourceManager.GetString("AlertTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string AlertTitleError {
            get {
                return ResourceManager.GetString("AlertTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string AlertTitleMessage {
            get {
                return ResourceManager.GetString("AlertTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password problem!.
        /// </summary>
        public static string AlertTitlePasswordProblem {
            get {
                return ResourceManager.GetString("AlertTitlePasswordProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string AlertTitleSuccess {
            get {
                return ResourceManager.GetString("AlertTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in.
        /// </summary>
        public static string ChInButton {
            get {
                return ResourceManager.GetString("ChInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out.
        /// </summary>
        public static string ChOuButton {
            get {
                return ResourceManager.GetString("ChOuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for your internet connection..
        /// </summary>
        public static string InternetConnectionLoss {
            get {
                return ResourceManager.GetString("InternetConnectionLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your pasword?.
        /// </summary>
        public static string LoginPageForgotPassword {
            get {
                return ResourceManager.GetString("LoginPageForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Beeple!.
        /// </summary>
        public static string LoginPageWelcome {
            get {
                return ResourceManager.GetString("LoginPageWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in/out.
        /// </summary>
        public static string McButton {
            get {
                return ResourceManager.GetString("McButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string MeButton {
            get {
                return ResourceManager.GetString("MeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string MrButton {
            get {
                return ResourceManager.GetString("MrButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandwiches.
        /// </summary>
        public static string MsButton {
            get {
                return ResourceManager.GetString("MsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 1.01.
        /// </summary>
        public static string NewRoomPageExampleName {
            get {
                return ResourceManager.GetString("NewRoomPageExampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string RegisterPageFirst {
            get {
                return ResourceManager.GetString("RegisterPageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string RegisterPageLast {
            get {
                return ResourceManager.GetString("RegisterPageLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added persons:.
        /// </summary>
        public static string RoomsPageAddedPersons {
            get {
                return ResourceManager.GetString("RoomsPageAddedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring this:.
        /// </summary>
        public static string RoomsPageBringThis {
            get {
                return ResourceManager.GetString("RoomsPageBringThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your favorite color and favorite animal?.
        /// </summary>
        public static string SentenceFavoriteColorAnimal {
            get {
                return ResourceManager.GetString("SentenceFavoriteColorAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the list to get back all orders..
        /// </summary>
        public static string SentenceRefreshListToNormal {
            get {
                return ResourceManager.GetString("SentenceRefreshListToNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if you are the responsible one for today:.
        /// </summary>
        public static string SentenceResponsible {
            get {
                return ResourceManager.GetString("SentenceResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose start time, end time and date:.
        /// </summary>
        public static string SentenceRoomsFilterPage {
            get {
                return ResourceManager.GetString("SentenceRoomsFilterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the name of your first toy?.
        /// </summary>
        public static string SentenceToy {
            get {
                return ResourceManager.GetString("SentenceToy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string SettingsPageLogout {
            get {
                return ResourceManager.GetString("SettingsPageLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string StringAdd {
            get {
                return ResourceManager.GetString("StringAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string StringAmount {
            get {
                return ResourceManager.GetString("StringAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and:.
        /// </summary>
        public static string StringAnd {
            get {
                return ResourceManager.GetString("StringAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer question 1.
        /// </summary>
        public static string StringAnswerQuestionOne {
            get {
                return ResourceManager.GetString("StringAnswerQuestionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer question 2.
        /// </summary>
        public static string StringAnswerQuestionTwo {
            get {
                return ResourceManager.GetString("StringAnswerQuestionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate total price.
        /// </summary>
        public static string StringCalculateTotalPrice {
            get {
                return ResourceManager.GetString("StringCalculateTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose who:.
        /// </summary>
        public static string StringChooseWho {
            get {
                return ResourceManager.GetString("StringChooseWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string StringConfirmPassword {
            get {
                return ResourceManager.GetString("StringConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        public static string StringDate {
            get {
                return ResourceManager.GetString("StringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all.
        /// </summary>
        public static string StringDeleteAllSandwiches {
            get {
                return ResourceManager.GetString("StringDeleteAllSandwiches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string StringDetails {
            get {
                return ResourceManager.GetString("StringDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string StringEnd {
            get {
                return ResourceManager.GetString("StringEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food and drinks provided:.
        /// </summary>
        public static string StringFDProvided {
            get {
                return ResourceManager.GetString("StringFDProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter date.
        /// </summary>
        public static string StringFilterDate {
            get {
                return ResourceManager.GetString("StringFilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: e-mail.
        /// </summary>
        public static string StringFilterEmail {
            get {
                return ResourceManager.GetString("StringFilterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter list.
        /// </summary>
        public static string StringFilterList {
            get {
                return ResourceManager.GetString("StringFilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter on e-mail.
        /// </summary>
        public static string StringFilterOnEmail {
            get {
                return ResourceManager.GetString("StringFilterOnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter room/date.
        /// </summary>
        public static string StringFilterRoomDate {
            get {
                return ResourceManager.GetString("StringFilterRoomDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter time.
        /// </summary>
        public static string StringFilterTime {
            get {
                return ResourceManager.GetString("StringFilterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter time/date.
        /// </summary>
        public static string StringFilterTimeDate {
            get {
                return ResourceManager.GetString("StringFilterTimeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food and drinks:.
        /// </summary>
        public static string StringFoodDrinks {
            get {
                return ResourceManager.GetString("StringFoodDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited persons:.
        /// </summary>
        public static string StringInvitedPersons {
            get {
                return ResourceManager.GetString("StringInvitedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptops.
        /// </summary>
        public static string StringLaptops {
            get {
                return ResourceManager.GetString("StringLaptops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material:.
        /// </summary>
        public static string StringMaterial {
            get {
                return ResourceManager.GetString("StringMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name event:.
        /// </summary>
        public static string StringNameEvent {
            get {
                return ResourceManager.GetString("StringNameEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New event.
        /// </summary>
        public static string StringNewEvent {
            get {
                return ResourceManager.GetString("StringNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string StringNo {
            get {
                return ResourceManager.GetString("StringNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal list.
        /// </summary>
        public static string StringNormalList {
            get {
                return ResourceManager.GetString("StringNormalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string StringOrder {
            get {
                return ResourceManager.GetString("StringOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiser:.
        /// </summary>
        public static string StringOrganiser {
            get {
                return ResourceManager.GetString("StringOrganiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present:.
        /// </summary>
        public static string StringPresent {
            get {
                return ResourceManager.GetString("StringPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string StringPresentButton {
            get {
                return ResourceManager.GetString("StringPresentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string StringRegister {
            get {
                return ResourceManager.GetString("StringRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements:.
        /// </summary>
        public static string StringRequirements {
            get {
                return ResourceManager.GetString("StringRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string StringResponsible {
            get {
                return ResourceManager.GetString("StringResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room:.
        /// </summary>
        public static string StringRoom {
            get {
                return ResourceManager.GetString("StringRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +0,20 for sauce.
        /// </summary>
        public static string StringSauceMoney {
            get {
                return ResourceManager.GetString("StringSauceMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True = smos / False = no smos.
        /// </summary>
        public static string StringSentenceSmos {
            get {
                return ResourceManager.GetString("StringSentenceSmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide.
        /// </summary>
        public static string StringShowHide {
            get {
                return ResourceManager.GetString("StringShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smos:.
        /// </summary>
        public static string StringSmos {
            get {
                return ResourceManager.GetString("StringSmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +0,50 for smos.
        /// </summary>
        public static string StringSmosMoney {
            get {
                return ResourceManager.GetString("StringSmosMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort bread:.
        /// </summary>
        public static string StringSortBread {
            get {
                return ResourceManager.GetString("StringSortBread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort event:.
        /// </summary>
        public static string StringSortEvent {
            get {
                return ResourceManager.GetString("StringSortEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string StringStart {
            get {
                return ResourceManager.GetString("StringStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string StringSubmit {
            get {
                return ResourceManager.GetString("StringSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        public static string StringTime {
            get {
                return ResourceManager.GetString("StringTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string StringTotal {
            get {
                return ResourceManager.GetString("StringTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport provided:.
        /// </summary>
        public static string StringTProvided {
            get {
                return ResourceManager.GetString("StringTProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport:.
        /// </summary>
        public static string StringTransport {
            get {
                return ResourceManager.GetString("StringTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where:.
        /// </summary>
        public static string StringWhere {
            get {
                return ResourceManager.GetString("StringWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which sandwiche:.
        /// </summary>
        public static string StringWhichSandwiche {
            get {
                return ResourceManager.GetString("StringWhichSandwiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White or brown.
        /// </summary>
        public static string StringWhiteBrown {
            get {
                return ResourceManager.GetString("StringWhiteBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With:.
        /// </summary>
        public static string StringWith {
            get {
                return ResourceManager.GetString("StringWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string StringYes {
            get {
                return ResourceManager.GetString("StringYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are succesfully checked in, enjoy your workday!.
        /// </summary>
        public static string SuccessfullCheckin {
            get {
                return ResourceManager.GetString("SuccessfullCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are succesfully checked out, see you next workday!.
        /// </summary>
        public static string SuccessfullCheckout {
            get {
                return ResourceManager.GetString("SuccessfullCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in/out.
        /// </summary>
        public static string TitleCheckinCheckoutPage {
            get {
                return ResourceManager.GetString("TitleCheckinCheckoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All events.
        /// </summary>
        public static string TitleEventsPage {
            get {
                return ResourceManager.GetString("TitleEventsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered eventslist.
        /// </summary>
        public static string TitleFilterEventsPage {
            get {
                return ResourceManager.GetString("TitleFilterEventsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered roomlist.
        /// </summary>
        public static string TitleFilterRoomsPage {
            get {
                return ResourceManager.GetString("TitleFilterRoomsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLoginPage {
            get {
                return ResourceManager.GetString("TitleLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string TitleMenuPage {
            get {
                return ResourceManager.GetString("TitleMenuPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New room reservation.
        /// </summary>
        public static string TitleNewRoomPage {
            get {
                return ResourceManager.GetString("TitleNewRoomPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string TitlePasswordPage {
            get {
                return ResourceManager.GetString("TitlePasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All reservations.
        /// </summary>
        public static string TitleRoomsPage {
            get {
                return ResourceManager.GetString("TitleRoomsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All orders.
        /// </summary>
        public static string TitleSandwichesOrdersPage {
            get {
                return ResourceManager.GetString("TitleSandwichesOrdersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sandwiches.
        /// </summary>
        public static string TitleSandwichesPage {
            get {
                return ResourceManager.GetString("TitleSandwichesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TitleSettingsPage {
            get {
                return ResourceManager.GetString("TitleSettingsPage", resourceCulture);
            }
        }
    }
}
